version: '3.4'

services:
  database:
    container_name: homestats_database
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=homestats 
      - INFLUXDB_HTTP_AUTH_ENABLED=True
      - INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD
      - INFLUXDB_USER
      - INFLUXDB_USER_PASSWORD
  
  scripts:
    container_name: homestats_scripts
    depends_on: 
      - database
    image: scripts
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
        - INFLUXDB_USER
        - INFLUXDB_USER_PASSWORD
        - HUEBRIDGE_KEY
        - LOGLEVEL=INFO

  grafana:
    container_name: homestats_grafana
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana_storage:/var/lib/grafana
      #- ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - database
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

volumes:
  influxdb_storage:
  grafana_storage:
