"""
Constants used in the homestats project
"""
TEMPERATURE_MEASURE = "Temperature"
PRESENCE_MEASURE = "Presence"
LIGHT_MEASURE = "LightLevel"
HUE_ZIGBEE_TEMPERATURE = "ZLLTemperature"
HUE_ZIGBEE_PRESENCE = "ZLLPresence"
HUE_ZIGBEE_LIGHT = "ZLLLightLevel"
SUPPORTED_SENSORS = (HUE_ZIGBEE_TEMPERATURE, HUE_ZIGBEE_PRESENCE, HUE_ZIGBEE_LIGHT)
